name: Build and Push Docker Image

on:
  push:
    branches:
      - stable

jobs:
  build:
    runs-on: ubuntu-latest  # This specifies the runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .github/deployment/node/Dockerfile  # Update with the path to your Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
